### ISSUE TITLE
[keyword] 3~4장 파일 포맷 및 B-트리 구현

### ISSUE THREAD

**Issue by wooyounggggg** [wooyounggggg/database-internals#12]
## 주제

'3장 - 파일 포맷' & '4장 - B-트리 구현'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#10

**Comment by seonWKim** [comment]
# Chapter 3
https://github.com/seonwoo960000/database-internals/blob/main/ch3/Chapter3.md

# Chapter 4 
https://github.com/seonwoo960000/database-internals/blob/main/ch4/Chapter4.md

**Comment by seonWKim** [comment]
# PostgreSQL에서 page 크기 이상의 데이터를 어떻게 저장하는가? TOAST 
- PostgreSQL 
  - 고정 크기 page(8KB)를 사용  
  - tuple을 저장할 때 multiple page에 걸쳐 저장되지 못하도록 구성
    - 크기가 큰 tuple을 저장할 수 없음 
    - 위와 같은 한계를 극복하기 위해 크기가 큰 tuple은 압축 이후 다수의 row로 분할됨 
- TOAST를 지원할 수 있는 data type 
  - 모든 data type이 TOAST를 지원할 필요는 없음(integer, long 등 굳이?)
  - TOAST를 지원하는 data type의 구조  
    - first 4 bytes: 해당 데이터의 길이 정보를 저장 
    - 그 이외의 구조는 자유로움

**Comment by wooyounggggg** [comment]
@seonwoo960000 
압축 대상 데이터가 많아진다면, overflow page에 데이터를 분할 저장하는 방식에 비해 성능이 떨어질 수 있을 것 같은데,
관련하여 생각해볼 가치가 있을 것 같네요!
