### ISSUE TITLE
[keyword] 6장 B-트리의 변형

### ISSUE THREAD

**Issue by wooyounggggg** [wooyounggggg/database-internals#18]
## 주제

'6장 B-트리의 변형'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#17

**Comment by seonWKim** [comment]
https://github.com/seonwoo960000/database-internals/tree/main/ch6
