### ISSUE TITLE
[keyword] 1~2장 개요 및 B-트리

### ISSUE THREAD

**Issue by wooyounggggg** [wooyounggggg/database-internals#7]
## 주제

'1장 - 소개 및 개요' & '2장 - B-트리'를 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#6

**Comment by seonWKim** [comment]
DBMS별로 secondary index의 구조가 내부적으로 어떤 차이점이 있는지, 그리고 차이점으로 인해 발생할 수 있는 문제가 무엇인지(성능 관점 등) 논의해보면 좋을 것 같습니다. MySQL과 PostgreSQL의 secondary index의 내부 구조는 다음과 같습니다. 

MySQL의 secondary 인덱스는 primary 인덱스와 함께 저장됩니다. 
[Indexes other than the clustered index are known as secondary indexes. In InnoDB, each record in a secondary index contains the primary key columns for the row, as well as the columns specified for the secondary index. InnoDB uses this primary key value to search for the row in the clustered index.](https://dev.mysql.com/doc/refman/5.7/en/innodb-index-types.html)
![image](https://github.com/wooyounggggg/database-internals/assets/69591622/d398ad4f-1209-4508-a18c-38727d859416)

하지만 PostgreSQL의 seconday 인덱스는 heap의 data page(디스크)에 위치한 tuple id를 가리킵니다. 참고로 PostgreSQL의 primary key도 tuple id를 가리키기 때문에 PostgreSQL은 primary key가 사실상 없다고 표현되기도 합니다. 
![image](https://github.com/wooyounggggg/database-internals/assets/69591622/43ae6009-7040-4c9a-9edb-37d0f8a6162b)

### Reference 
https://medium.com/@hnasr/postgres-vs-mysql-5fa3c588a94e

**Comment by wooyounggggg** [comment]
## p.24, p.26 Gossip?
> p.24 이 책은 "이 데이터베이스는 **가십**을 통해 멤버십을 전파한다", ...

> p.26 결과적 일관성을 보장하는 시스템에서 데이터의 일관성을 유지하기 위해 사용하는 안티-엔트로피 알고리즘과 데이터 전파를 위해 사용하는 **가십** 프로토콜도 알아본다.

### 가십?
이후 책에서 등장할 것이기 때문에, 간단하게 gpt에 질문

**Q) 가십 프로토콜이 뭐야?**
A) 가십 프로토콜(Gossip Protocol)은 컴퓨터 네트워크에서 사용되는 분산 시스템에서 정보를 전파하는 방법 중 하나입니다. 이 프로토콜은 대규모 네트워크에서 노드 간에 데이터를 공유하고 업데이트하는 데 사용됩니다.

가십 프로토콜은 주로 peer-to-peer (P2P) 네트워크와 같은 분산 시스템에서 사용됩니다. P2P 네트워크는 중앙 서버 없이 컴퓨터가 서로 직접 연결되어 데이터를 교환하는 방식으로 작동합니다. 가십 프로토콜은 이러한 분산 시스템에서 데이터의 일관성과 동기화를 유지하기 위해 사용됩니다.

가십 프로토콜은 각 노드가 서로에게 정보를 무작위로 전파하는 방식으로 작동합니다. 각 노드는 주기적으로 다른 노드에게 자신이 가지고 있는 정보를 랜덤하게 선택하여 전파합니다. 이 정보는 이웃 노드로 전달되고, 이웃 노드는 동일한 과정을 반복하여 정보를 전파합니다. 이러한 과정을 통해 네트워크 전체에 데이터가 분산되고, 모든 노드가 최신 정보를 유지할 수 있게 됩니다.

가십 프로토콜은 네트워크의 안정성과 신뢰성을 향상시키는 데 도움이 됩니다. 한 노드에서 발생한 업데이트나 변경 사항이 빠르게 전파되어 모든 노드가 일관된 상태를 유지할 수 있습니다. 또한, 가십 프로토콜은 중앙 집중식 시스템에 비해 확장성과 내결함성이 높은 장점을 가지고 있습니다.

가십 프로토콜은 분산 데이터베이스 시스템, 블록체인, 파일 공유 네트워크 등 다양한 분산 시스템에서 사용될 수 있습니다.

**Q) 컴퓨터 과학에서 가십이 무슨 의미야?**
A) 컴퓨터 과학에서 "가십(gossip)"은 정보를 무작위로 전파하거나 교환하는 프로세스나 알고리즘을 가리키는 용어입니다. 이 용어는 분산 시스템에서 데이터 또는 메시지를 노드 간에 효율적으로 전달하는 방법을 설명하는 데 사용됩니다.

가십은 일반적으로 P2P (peer-to-peer) 네트워크에서 많이 사용되며, 이러한 네트워크는 중앙 서버가 없이 컴퓨터가 직접 연결되어 데이터를 교환하는 방식으로 작동합니다. 각 노드는 주변 노드에게 정보를 무작위로 전달하고, 이러한 전파 과정을 통해 네트워크 전체에 데이터가 분산됩니다.

가십은 분산 시스템에서 중요한 역할을 수행합니다. 데이터의 복제, 동기화, 일관성 유지 등을 위해 가십 프로토콜이 사용될 수 있습니다. 예를 들어, 분산 데이터베이스 시스템에서는 가십을 사용하여 데이터베이스의 복제본 간에 업데이트를 전파하고 일관된 상태를 유지합니다. 또한, 블록체인 기술에서도 가십 알고리즘을 사용하여 새로운 블록을 네트워크에 전파하고 검증하는 역할을 수행합니다.

컴퓨터 과학에서의 "가십"은 정보의 전파 및 교환 방식을 설명하는 데 사용되며, 분산 시스템의 안정성과 성능을 향상시키는 데 중요한 개념입니다.

**Comment by seonWKim** [comment]
# Introduction
- 데이터베이스 선정 시 고려할 사항
    - 사용하고자하는 쿼리를 지원하는가
    - 저장하고자하는 데이터의 양을 DB가 감당할 수 있는가
    - 단일 DB node에서 처리할 수 있는 읽기/쓰기 처리량
    - 시스템에서 필요한 DB node의 수
    - DB 확장을 어떻게 하는가
    - 유지보수 프로세스
- YCSB(Yahoo! Cloud Serving Benchmark)
    - 시중에 다양한 데이터베이스가 존재
        - 비슷한 유형의 데이터베이스 사이에서 어떤걸 선택해야하는지 ....
- YCSB project is to develop a framework and common set of workloads for evaluating the performance of different "key-value" and "cloud" serving stores
- 구성
    - YCSB client: Workload generator
    - Core workloads: Generator에 의해 실행될 workload scenario

# Chapter 1. 
## 데이터베이스 분류 
### OLTP vs OLAP 
- OLTP
  - 짧은 트랜잭션 대상 
- OLAP 
  - 복잡한 분석 작업 
  - 정형화된 쿼리가 아닌 경우 다수 존재

## 데이터베이스 아키텍처 
- Transport 
  - cluster communication 
  - client communication 
- Query processor 
  - query parser 
  - query optimizer 
- Execution engine 
  - remote execution 
  - local execution 
- Storage engine 
  - transaction manager: tx 관리 
  - lock manager: tx를 위해 database object locking 
  - access methods: disk의 데이터 조회 
  - buffer manager: memory에 page 캐싱 
  - recovery manager: failure에 대비한 recovery 관련

## Memory vs Disk Based DBMS 
- 구조와 접근 속도로 인해 효율적으로 사용하는 방법 자체가 다름 
  - memory based  
    - disk에 비해 빠름 
    - 메모리를 자유롭게 할당받아 사용 가능 
  - disk based 
    - disk에 위치한 데이터를 식별하고 참조할 수 있어야 함 
    - serialization / deserialization 고려 
    - fragmentation 관리 

### Disk Based DBMS Durability 
- Sequential log를 활용 
  - WAL (Write Ahead Log)
  - Back up copy: 비동기 + 배치 형태로 적용됨 
- WAL를 활용해서 데이터베이스 복구에 사용
  - checkpointing: 디스크에 성공적을 반영이 완료된 부분을 표시 
- 각 DBMS에서 WAL를 사용하는 방법에 대한 조사

## Column VS Row Oriented DBMS 
- Row oriented 
  - block 단위로 데이터를 조회
    - query에서 조회하고자 하는 데이터가 block 내부에 존재하는 경우 유용
    - 특정 컬럼만 조회하는 경우 효율적이지 않음
- Column oriented 
  - 동일 컬럼을 조회하는 쿼리에 유용 
    - 컬럼별 효율적인 압축 알고리즘을 사용할 수 있다는 장점 
    - CPU 효율도 상승함(vectorized instruction)

### Wide column store 
- Column oriented database와 다른 개념 
  - BigTable, HBase 
- Data는 다차원 map의 형태로 표시됨 

## Data Files & Index Files 
- Data file
  - Data를 저장 
  - 구현 방식 
    - IOT(Index organized table)
      - 데이터를 인덱스와 함께 저장하는 방식 
    - Heap organized table
      - 쓰기 순서대로 데이터가 저장됨 
      - 데이터가 저장된 위치를 가리키는 별도의 자료구조가 필요 
    - Hash organized table 
      - key의 해시값을 기준으로 value가 담길 bucket을 결정  
- Index file 
  - secondary kek 
    - primary key와 함꼐 저장되거나(MySQL)
    - heap file/IOT에서 해당되는 데이터의 offset을 가리킬 수 있음(PostgreSQL)
- * MySQL과 PostgreSQL의 index 구성 차이

# Chapter 2 
## B-Tree 
- Binary tree(X) -> Balanced tree(? 불분명한 어원)
- Disk based 자료구조로 일반 binary tree를 사용한다면 
  - low fanout, tree height가 높기 때문에 disk 탐색 비용이 큼 
  - rebalancing이 자주 발생
  - 관련성이 높을 수 있는 인접한 노드가 디스크 상에서 멀리 위치할 수 있음 -> 지역성이 떨어짐

## Disk  
- HDD 
  - random read 취약 
  - sector 단위로 읽기/쓰기 
- SSD 
  - ![image](https://github.com/wooyounggggg/database-internals/assets/69591622/7e624d10-2c9e-49d9-8dea-1fab4cad057e)
  - memory cell -> string -> array -> page -> block -> plane -> die 
    - cell: 한개 또는 다수의 bit 
    - page: 
      - 2 ~ 16kb 
      - SSD의 최소 쓰기 단위
      - empty memory cell에만 쓰기작업이 필요 -> memory cell이 차있으면 삭제 작업 필요 
    - block: 
      - 64 ~ 512 page 
      - 최소 삭제 단위
    - HDD에 비해 random read 성능이 덜 나쁘긴 하지만... 여전히 random read는 SSD의 성능에도 악영향 
      - prefetching 
      - reading contiguous page 
      - internal parallelism 
- OS에서 disk의 읽고 쓰는 작업을 추상화 
  - block device abstraction 
  - 디스크에서 작은 데이터를 읽더라도 block 통째로 읽어야 함 

## Ubiquitous B-Trees 
- 구성 
  - root node 
    - parent가 없는 노드 
  - internal node 
    - root과 leaf node를 연결 
  - leaf node 
    - 데이터가 저장됨 
    - range scan 효율을 높이기 위해 leaf node간 가리키는 sibling pointer을 두기도 함 
- B-tree 분할과 병합 
  - 분할(split)
    1. 새로운 노드를 추가 
    2. 분할하고자하는 노드로부터 데이터 절반을 새로운 ㄴ드로 이동 
    3. 새로운 노드를 B-Tree에 위치시킴 
    4. 부모 노드에서 새로운 노드를 가리키도록 수정 
  - 병합(merge)
    1. 오른쪽 노드의 데이터를 왼쪽 노드로 이동 
    2. 부모 노드에서 오른쪽 노드의 포인터 삭제 
    3. 오른쪽 노드 삭제
