### ISSUE TITLE
[question] 스토리지 엔진의 노드란 무엇을 의미하는 것일까요?

### ISSUE THREAD

**Issue by wooyounggggg** [wooyounggggg/database-internals#8]
## 질문

책 p.31에서 다음 문장을 볼 수 있습니다.

> 스토리지 엔진(또는 데이터베이스 엔진)은 DBMS에서 데이터를 메모리와 디스크에 저장하고 검색 및 관리하는 소프트웨어 컴포넌트로서 각 **노드**에 데이터를 영구 저장한다.

여기서 **노드**가 가리키는 것이 추상적으로 느껴지는데, 어떤 것을 의미한다고 생각하시는지 궁금합니다.

## 연관 챕터

#6

**Comment by seonWKim** [comment]
제 짧은 식견으로는 데이터베이스 프로세스가 실행되는 컴퓨팅 노드를 의미하는 것 같습니다!
